# ----------------------------------------------------- 
# General window decoration
# name: "Default"
# ----------------------------------------------------- 
#

decoration {
    rounding = 9
    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = on
        ignore_opacity = true
        xray = true
        noise=0.1
        contrast=1
        # blurls = waybar
    }
    active_opacity = 1.0
    # inactive_opacity = 0.8
    fullscreen_opacity = 1.0

    # drop_shadow = true
    # shadow_range = 30
    # shadow_render_power = 3
    # col.shadow = 0x66000000
}
group{ 
  groupbar{
    enabled = true
    col.active = rgba(4f5b58ff)
    col.inactive = rgba(1e2327ff)
    text_color = rgba(A09986ff)
    gradients=true
    font_family=JetBrainsMonoNerdFont
  }
  col.border_active = rgba(A7C080ff)
  col.border_inactive = rgba(3b4252ff)
}
