# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule = tile on, match:class Microsoft-edge
windowrule = tile on, match:class Brave-browser
windowrule = tile on, match:class Chromium
windowrule = tile on, match:class libreoffice-calc
windowrule = float off, match:class libreoffice-calc
windowrule = float on, center on, size 900 600, match:title floatty
windowrule = float on, center on, size 900 600, match:class org.pulseaudio.pavucontrol
windowrule = float on, match:class blueman-manager-wrapped
windowrule = float on, match:class blueman-manager
windowrule = float on, match:class nm-connection-editor
windowrule = float on, center on, size 800 600, match:class ^(qalculate-gtk)$
windowrule = float on, match:class matplotlib
windowrule = float on, match:class feh
windowrule = float on, match:class imv

windowrule = opacity 1 override 1 override, match:class vlc
windowrule = opacity 0.85 override 0.85 override, match:title ^(zsh)$
windowrule = opacity 0.85 override 0.85 override, match:title ^(tmux)$
windowrule = opacity 0.85 override 0.85 override, match:class com.mitchellh.ghostty

# Browser Picture in Picture
windowrule = float on, match:class ^(Picture-in-Picture)$
windowrule = pin on, match:class ^(Picture-in-Picture)$
windowrule = move 69.5% 4%, match:class ^(Picture-in-Picture)$

# Pesky libre tools rendering

windowrule = workspace 8, match:class ^(libreoffice.*|soffice)$


windowrule {
  name = rename-small
  match:class = thunar
  match:initial_title = ^Rename.*$
  float = on
}
