# Only for Places that have one window
workspace = w[t1]m[DP-3], gapsout:40 460 30 460
workspace = w[2-3]m[DP-3], gapsout:60 220 60 220
workspace = w[t1]m[HDMI-A-3], gapsout:40 160 30 160
workspace = w[2-3]m[HDMI-A-3], gapsout:60 80 60 80

workspace = w[t1]m[DP-2], gapsout:40 460 30 460
workspace = w[2-3]m[DP-2], gapsout:60 220 60 220
workspace = w[t1]m[HDMI-A-2], gapsout:40 160 30 160
workspace = w[2-3]m[HDMI-A-2], gapsout:60 80 60 80
workspace = w[1], shadow:true
